//
// Created by Horatiu on 03-Mar-19.
//

#ifndef LAB1OPTIONAL_EDGEDOESNOTEXISTEXCEPTION_H
#define LAB1OPTIONAL_EDGEDOESNOTEXISTEXCEPTION_H


class EdgeDoesNotExistException
{

};


#endif //LAB1OPTIONAL_EDGEDOESNOTEXISTEXCEPTION_H
