//
// Created by Horatiu on 03-Mar-19.
//

#ifndef LAB1OPTIONAL_EDGEALREADYEXISTSEXCEPTION_H
#define LAB1OPTIONAL_EDGEALREADYEXISTSEXCEPTION_H


class EdgeAlreadyExistsException
{

};


#endif //LAB1OPTIONAL_EDGEALREADYEXISTSEXCEPTION_H
