//
// Created by Horatiu on 03-Mar-19.
//

#ifndef LAB1OPTIONAL_VERTEXDOESNOTEXISTEXCEPTION_H
#define LAB1OPTIONAL_VERTEXDOESNOTEXISTEXCEPTION_H


class VertexDoesNotExistException
{

};


#endif //LAB1OPTIONAL_VERTEXDOESNOTEXISTEXCEPTION_H
