//
// Created by Horatiu on 03-Mar-19.
//

#ifndef LAB1OPTIONAL_VERTEXALREADYEXISTSEXCEPTION_H
#define LAB1OPTIONAL_VERTEXALREADYEXISTSEXCEPTION_H


class VertexAlreadyExistsException
{

};


#endif //LAB1OPTIONAL_VERTEXALREADYEXISTSEXCEPTION_H
